clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - make deps gen
    - make test test_postgres test_mysql
    - make build build_static deb docs

compose:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: drone/drone
    tag:
      - "latest" 
      - "0.4"
    when:
      repo: drone/drone
      branch: master

  docker:
    registry: shippedrepos-docker-drone.bintray.io
    repo: drone
    email: $$DOCKER_EMAIL
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    tag:
      - latest
      - "$${COMMIT:0:8}"
    when:
      owner: CiscoCloud
      branch: shipped

  docker:
    registry: shippedrepos-docker-drone.bintray.io
    repo: benschumacher/drone
    email: $$DOCKER_EMAIL
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    tag:
      - "pr.${CI_PULL_REQUEST}"
    when:
      owner: CiscoCloud
      event: pull_request

